CREATE TABLE T_DOCUMENT_DOC(
    DOC_ID 		  NUMBER(6)		NOT NULL,
    DOC_LIBELLE   VARCHAR2(48)	NOT NULL,
    DOC_TYPE	  VARCHAR2(48)	NOT NULL,
    DOC_DESC	  VARCHAR(256)	NOT NULL,
    DOC_FICHIER	  VARCHAR2(64)	NOT NULL,
    DOC_DEBUT     DATE			NOT NULL,
    DOC_FIN	      DATE,
    DOC_CONTENU   BLOB
)
TABLESPACE H_TBS_HCONTACTS_DATA;

ALTER TABLE HOTLINE.T_DOCUMENT_DOC ADD 
CONSTRAINT PK_DOC
 PRIMARY KEY (DOC_ID)
 ENABLE
 VALIDATE;
 
 ALTER TABLE HOTLINE.T_DOCUMENT_DOC ADD 
CONSTRAINT UK_DOC
 UNIQUE (DOC_LIBELLE)
 ENABLE
 VALIDATE;

GRANT INSERT,SELECT,UPDATE,DELETE ON T_DOCUMENT_DOC TO U_HCONTACTS;

CREATE SEQUENCE HOTLINE.SEQ_ID_DOC START WITH 1 MAXVALUE 999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
GRANT SELECT ON HOTLINE.SEQ_ID_DOC TO U_HCONTACTS;

CREATE TABLE T_DOCUMENT_MODELEPROC_DMP(
    DMP_DOC_ID 		  NUMBER(6),
    DMP_MODPROC_ID	  NUMBER(6)
)
TABLESPACE H_TBS_HCONTACTS_DATA;
GRANT INSERT,SELECT,UPDATE,DELETE ON T_DOCUMENT_MODELEPROC_DMP TO U_HCONTACTS;

ALTER TABLE HOTLINE.T_DOCUMENT_MODELEPROC_DMP ADD 
CONSTRAINT FK_DMP_DOC
 FOREIGN KEY (DMP_DOC_ID)
 REFERENCES HOTLINE.T_DOCUMENT_DOC (DOC_ID)
 ENABLE
 VALIDATE;
 
 ALTER TABLE HOTLINE.T_DOCUMENT_MODELEPROC_DMP ADD 
CONSTRAINT FK_DMP_MDP
 FOREIGN KEY (DMP_MODPROC_ID)
 REFERENCES HOTLINE.MODELE_PROCEDURE (ID)
 ENABLE
 VALIDATE;