=> en HOTLINE/HOTLINE
CREATE TABLE HOTLINE.MODELE_PEC ( 
    ID                          NUMBER(3) NOT NULL, 
    LIBELLE						VARCHAR2(24) NOT NULL,
    OPERATEUR                   VARCHAR2(12) NOT NULL, 
    ORGANISME                   VARCHAR2(9) NOT NULL,
    ENVOI_FAX                   NUMBER(1) NULL,
    FAX                         VARCHAR2(16) NULL,  
    ENVOIL_COURRIEL             NUMBER(1) NULL, 
    COURRIEL                    VARCHAR2(64) NULL,
    BENEFICIAIRE_PERMIS			NUMBER(1) DEFAULT 1,
    FOURNISSEUR_PERMIS			NUMBER(1) DEFAULT 0,
    CONSTRAINT PK_MOD_PEC PRIMARY KEY(ID) 
) 
TABLESPACE H_TBS_HCONTACTS_DATA;

GRANT SELECT,INSERT,UPDATE,DELETE ON HOTLINE.MODELE_PEC TO U_HCONTACTS;

CREATE SEQUENCE HOTLINE.SEQ_ID_MODPEC START WITH 1 MAXVALUE 999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
GRANT SELECT ON HOTLINE.SEQ_ID_MODPEC TO U_HCONTACTS;

CREATE OR REPLACE TRIGGER HOTLINE.trg_id_modpec
 BEFORE INSERT ON HOTLINE.MODELE_PEC FOR EACH ROW
BEGIN
 SELECT hotline.seq_id_modpec.NEXTVAL INTO :new.ID FROM DUAL;
END;
/

ALTER TABLE HOTLINE.SCENARIO_EVENEMENT
ADD (MODELEPEC_ID NUMBER(3));

ALTER TABLE HOTLINE.SCENARIO_EVENEMENT ADD 
CONSTRAINT FK_SCE_MODPEC
 FOREIGN KEY (MODELEPEC_ID)
 REFERENCES HOTLINE.MODELE_PEC (ID)
 ENABLE
 VALIDATE;

CREATE TABLE RATTACHEMENT_PEC(
    scenario_id NUMBER(6)     NOT NULL,
    motif_id    NUMBER(8)     DEFAULT NULL,
    s_motif_id    NUMBER(10)  DEFAULT NULL,
    point_id    NUMBER(12)    DEFAULT NULL,
    s_point_id    NUMBER(14)  DEFAULT NULL,
    modelepec_id NUMBER(3)    NOT NULL
)
TABLESPACE H_TBS_HCONTACTS_DATA;

GRANT SELECT,INSERT,UPDATE,DELETE ON RATTACHEMENT_PEC TO U_HCONTACTS;

ALTER TABLE HOTLINE.RATTACHEMENT_PEC ADD 
CONSTRAINT FK_SRP_MODPEC
 FOREIGN KEY (MODELEPEC_ID)
 REFERENCES HOTLINE.MODELE_PEC (ID)
 ENABLE
 VALIDATE;
 
ALTER TABLE HOTLINE.RATTACHEMENT_PEC ADD 
CONSTRAINT FK_SRP_SCE
 FOREIGN KEY (SCENARIO_ID)
 REFERENCES HOTLINE.SCENARIO(ID)
 ENABLE
 VALIDATE; 
 
ALTER TABLE HOTLINE.RATTACHEMENT_PEC ADD 
CONSTRAINT FK_SRP_MOTIF
 FOREIGN KEY (MOTIF_ID)
 REFERENCES HOTLINE.MOTIFAPPEL(ID)
 ENABLE
 VALIDATE;
 
ALTER TABLE HOTLINE.RATTACHEMENT_PEC ADD 
CONSTRAINT FK_SRP_SMOTIF
FOREIGN KEY (S_MOTIF_ID)
 REFERENCES HOTLINE.SMOTIFAPPEL(ID)
 ENABLE
 VALIDATE;
 
ALTER TABLE HOTLINE.RATTACHEMENT_PEC ADD 
CONSTRAINT FK_SRP_POINT
 FOREIGN KEY (POINT_ID)
 REFERENCES HOTLINE.POINT(ID)
 ENABLE
 VALIDATE;
 
ALTER TABLE HOTLINE.RATTACHEMENT_PEC ADD 
CONSTRAINT FK_SRP_SPOINT
 FOREIGN KEY (S_POINT_ID)
 REFERENCES HOTLINE.SPOINT(ID)
 ENABLE
 VALIDATE;   

insert into CODES
   (JDOCLASS, ALIAS, LIBELLE, DEFAUT, ORDRE)
 Values
   ('hosta.crm.impl.codes.Cloture', 'AUTRECAMP', 'Autre Campagne', 0, 9); 
 
=> En GED/GED 
--insert into T_REFS_STATS_RST
--   (RST_ID, RST_LIBELLE, RST_ALIAS, RST_RSF_ID, RST_ACTIF)
-- Values
--   (201, 'Demande de PEC H.Contact', 'PEC_HCONTACTS', 42, 1); 
 
begin
ps_creationmotifdossier('Demande PEC',201);
end;
/