-- HOTLINE
DROP TABLE HOTLINE.MODELE_PROCEDURE;
CREATE TABLE HOTLINE.MODELE_PROCEDURE(
    ID            		NUMBER(4)      NOT NULL,
    LIBELLE        		VARCHAR2(48)   NOT NULL,
    TYPE        		VARCHAR2(48)   NOT NULL,
    MAIL_OBJET       	VARCHAR2(64)   NOT NULL,
    MAIL_INVITE      	VARCHAR2(320)  NOT NULL,
    RECAP_ADH			NUMBER(1)	   DEFAULT 0 NOT NULL ,		
    MAIL_CORPS       	VARCHAR2(2400) NOT NULL,
    MAIL_SIGNATURE		VARCHAR2(320)  NOT NULL,
    RECAP_CENTREGESTION NUMBER(1)	   DEFAULT 0 NOT NULL ,
    TYPE_DESTINATAIRE	VARCHAR2(1)    DEFAULT 'I'
)
TABLESPACE H_TBS_HCONTACTS_DATA;

ALTER TABLE HOTLINE.MODELE_PROCEDURE ADD 
CONSTRAINT PK_MODPROCEDURE
 PRIMARY KEY (ID);

ALTER TABLE HOTLINE.MODELE_PROCEDURE ADD 
CONSTRAINT UK_MODPROCEDURE
 UNIQUE (LIBELLE); 
 
GRANT SELECT,INSERT,UPDATE,DELETE ON MODELE_PROCEDURE TO U_HCONTACTS;

DROP SEQUENCE HOTLINE.SEQ_ID_MODPROCEDURE;
CREATE SEQUENCE HOTLINE.SEQ_ID_MODPROCEDURE START WITH 1 MAXVALUE 999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
GRANT SELECT ON HOTLINE.SEQ_ID_MODPROCEDURE TO U_HCONTACTS;

CREATE OR REPLACE TRIGGER HOTLINE.trg_id_modprocedure
 BEFORE INSERT ON HOTLINE.MODELE_PROCEDURE FOR EACH ROW
BEGIN
 SELECT hotline.seq_id_modprocedure.NEXTVAL INTO :new.ID FROM DUAL;
END;
/

DROP TABLE HOTLINE.RATTACHEMENT_PROCEDURE;
CREATE TABLE HOTLINE.RATTACHEMENT_PROCEDURE ( 
    SCENARIO_ID         NUMBER(6) NOT NULL,
    MODPROCEDURE_ID     NUMBER(4) NOT NULL, 
    MOTIF_ID            NUMBER(8) DEFAULT NULL, 
    S_MOTIF_ID          NUMBER(10) DEFAULT NULL, 
    POINT_ID            NUMBER(12) DEFAULT NULL, 
    S_POINT_ID          NUMBER(14) DEFAULT NULL ) 
TABLESPACE H_TBS_HCONTACTS_DATA;

GRANT DELETE, INSERT, SELECT, UPDATE ON HOTLINE.RATTACHEMENT_PROCEDURE TO U_HCONTACTS;

ALTER TABLE HOTLINE.RATTACHEMENT_PROCEDURE ADD 
CONSTRAINT FK_RPM_MODPRC
 FOREIGN KEY (MODPROCEDURE_ID)
 REFERENCES HOTLINE.MODELE_PROCEDURE(ID)
 ENABLE
 VALIDATE;
 
ALTER TABLE HOTLINE.RATTACHEMENT_PROCEDURE ADD 
CONSTRAINT FK_RPM_SCE
 FOREIGN KEY (SCENARIO_ID)
 REFERENCES HOTLINE.SCENARIO(ID)
 ENABLE
 VALIDATE;
 
ALTER TABLE HOTLINE.RATTACHEMENT_PROCEDURE ADD 
CONSTRAINT FK_RPM_MOTIF
 FOREIGN KEY (MOTIF_ID)
 REFERENCES HOTLINE.MOTIFAPPEL(ID)
 ENABLE
 VALIDATE;

ALTER TABLE HOTLINE.RATTACHEMENT_PROCEDURE ADD 
CONSTRAINT FK_RPM_SMOTIF
 FOREIGN KEY (S_MOTIF_ID)
 REFERENCES HOTLINE.SMOTIFAPPEL(ID)
 ENABLE
 VALIDATE;

ALTER TABLE HOTLINE.RATTACHEMENT_PROCEDURE ADD 
CONSTRAINT FK_RPM_POINT
 FOREIGN KEY (POINT_ID)
 REFERENCES HOTLINE.POINT(ID)
 ENABLE
 VALIDATE;

ALTER TABLE HOTLINE.RATTACHEMENT_PROCEDURE ADD 
CONSTRAINT FK_RPM_SPOINT
 FOREIGN KEY (S_POINT_ID)
 REFERENCES HOTLINE.SPOINT(ID)
 ENABLE
 VALIDATE;

-- GED
begin
ps_creationmotifdossier('Envoi de procédure par mail',28);
end;
/